local localization = {}

local translations = {
    pt = {
        title = "CONTROLES",
        subtitle = "Configuração rápida do gamepad",
        tab_controls = "CONTROLES",
        tab_visual = "VISUAL",
        tab_layout = "LAYOUT",
        controls_on_screen = "Controles na tela",
        controls_visible = "Visíveis durante o jogo",
        controls_hidden = "Ocultos; ajustes continuam acessíveis",
        direction_type = "TIPO DE DIREÇÃO",
        direction_fixed = "Fixo",
        direction_dynamic = "Livre",
        direction_dpad4 = "D-pad 4",
        direction_dpad8 = "D-pad 8",
        direction_style = "ESTILO DO DIRECIONAL",
        analog_modes_only = "Disponível nos modos analógicos",
        dead_zone = "ZONA MORTA",
        analog_response = "Resposta do analógico",
        scale = "ESCALA",
        direction_size = "Tamanho do direcional",
        button_size = "Tamanho dos botões",
        visibility = "VISIBILIDADE",
        opacity = "Opacidade",
        button_appearance = "APARÊNCIA DOS BOTÕES",
        variation = "Variação",
        layout_intro = "Posicione os controles onde sua mão alcança melhor.",
        layout_help = "O editor abre o jogo sem o painel e permite arrastar cada controle diretamente.",
        edit_positions = "Editar posições",
        edit_hint = "Arraste Z, X, C e o direcional; conclua quando terminar.",
        reset_positions_only = "Repor somente as posições",
        keep_visual_settings = "Mantém tamanho, direção e opacidade.",
        confirm_reset = "Confirmar restauração",
        restore_defaults = "Restaurar padrões",
        done = "Concluir",
        edit_mode = "MODO DE EDIÇÃO • ARRASTE OS CONTROLES",
        reset_positions = "Repor posições",
    },
    en = {
        title = "CONTROLS",
        subtitle = "Quick gamepad settings",
        tab_controls = "CONTROLS",
        tab_visual = "VISUAL",
        tab_layout = "LAYOUT",
        controls_on_screen = "On-screen controls",
        controls_visible = "Visible during gameplay",
        controls_hidden = "Hidden; settings remain accessible",
        direction_type = "DIRECTION TYPE",
        direction_fixed = "Fixed",
        direction_dynamic = "Free",
        direction_dpad4 = "D-pad 4",
        direction_dpad8 = "D-pad 8",
        direction_style = "DIRECTION STYLE",
        analog_modes_only = "Available in analog modes",
        dead_zone = "DEAD ZONE",
        analog_response = "Analog response",
        scale = "SCALE",
        direction_size = "Direction size",
        button_size = "Button size",
        visibility = "VISIBILITY",
        opacity = "Opacity",
        button_appearance = "BUTTON APPEARANCE",
        variation = "Variant",
        layout_intro = "Position controls where your hands can reach.",
        layout_help = "The editor hides the panel so you can drag each control directly.",
        edit_positions = "Edit positions",
        edit_hint = "Drag Z, X, C and the direction control; finish when done.",
        reset_positions_only = "Reset positions only",
        keep_visual_settings = "Keeps size, direction, and opacity.",
        confirm_reset = "Confirm reset",
        restore_defaults = "Restore defaults",
        done = "Done",
        edit_mode = "EDIT MODE • DRAG THE CONTROLS",
        reset_positions = "Reset positions",
    },
    es = {
        title = "CONTROLES",
        subtitle = "Ajustes rápidos del mando",
        tab_controls = "CONTROLES",
        tab_visual = "VISUAL",
        tab_layout = "POSICIÓN",
        controls_on_screen = "Controles en pantalla",
        controls_visible = "Visibles durante el juego",
        controls_hidden = "Ocultos; los ajustes siguen accesibles",
        direction_type = "TIPO DE DIRECCIÓN",
        direction_fixed = "Fijo",
        direction_dynamic = "Libre",
        direction_dpad4 = "D-pad 4",
        direction_dpad8 = "D-pad 8",
        direction_style = "ESTILO DIRECCIONAL",
        analog_modes_only = "Disponible en modos analógicos",
        dead_zone = "ZONA MUERTA",
        analog_response = "Respuesta analógica",
        scale = "ESCALA",
        direction_size = "Escala direccional",
        button_size = "Escala de botones",
        visibility = "VISIBILIDAD",
        opacity = "Opacidad",
        button_appearance = "ASPECTO DE LOS BOTONES",
        variation = "Variación",
        layout_intro = "Coloca los controles donde tu mano llegue mejor.",
        layout_help = "El editor abre el juego sin el panel y permite arrastrar cada control.",
        edit_positions = "Editar posiciones",
        edit_hint = "Arrastra Z, X, C y el control direccional; finaliza al terminar.",
        reset_positions_only = "Restablecer solo posiciones",
        keep_visual_settings = "Mantiene escala, dirección y opacidad.",
        confirm_reset = "Confirmar restauración",
        restore_defaults = "Restaurar valores",
        done = "Finalizar",
        edit_mode = "MODO DE EDICIÓN • ARRASTRA LOS CONTROLES",
        reset_positions = "Restablecer posiciones",
    },
}

local function currentLanguage()
    local language = tostring(_G.KRISTAL_LAUNCHER_LANGUAGE or "en"):lower():gsub("_", "-")
    language = language:match("^([a-z]+)") or "en"
    if translations[language] then return language end
    return "en"
end

function localization.get(key)
    local language = currentLanguage()
    return translations[language][key] or translations.en[key] or key
end

return localization
